[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc"]

[phases.install]
cmds = [
  "npm install --prefix frontend",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "python3 backend/serve_prod.py"
